##**TASK-1 Iris Flowers Classification ML Project :**

This particular ML project is usually referred to as the “Hello World” of Machine Learning. The iris flowers dataset contains numeric attributes, and it is perfect for beginners to learn about supervised ML algorithms, mainly how to load and handle data. Also, since this is a small dataset, it can easily fit in memory without requiring special transformations or scaling capabilities.

NAME: C.N.Vigneshwar

IMPORT THE REQUIRED PACKAGES AND LIBRARIES

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC,LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,  classification_report,confusion_matrix
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from  tensorflow.keras.optimizers import SGD

IMPORTING THE IRIS DATASET

In [3]:
df = pd.read_csv('Iris.csv',
                names=["Sepal_Length_in_cm","Sepal_Width_in_cm","Petal_Length_in_cm","Petal_Width_in_cm","Species_Flower"])

REMOVING UNNCESSARY COLUMNS

In [4]:
df = df.drop("Id")

In [5]:
df

Sepal_Length_in_cm Sepal_Width_in_cm Petal_Length_in_cm Petal_Width_in_cm  \
1                  5.1               3.5                1.4               0.2   
2                  4.9               3.0                1.4               0.2   
3                  4.7               3.2                1.3               0.2   
4                  4.6               3.1                1.5               0.2   
5                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
146                6.7               3.0                5.2               2.3   
147                6.3               2.5                5.0               1.9   
148                6.5               3.0                5.2               2.0   
149                6.2               3.4                5.4               2.3   
150                5.9               3.0                5.1               1.8   

     Species_Flower  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
5       Iris-setosa  
..              ...  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150  Iris-virginica  

[150 rows x 5 columns]

PERFORMING EDA

In [6]:
df.shape

(150, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Sepal_Length_in_cm  150 non-null    object
 1   Sepal_Width_in_cm   150 non-null    object
 2   Petal_Length_in_cm  150 non-null    object
 3   Petal_Width_in_cm   150 non-null    object
 4   Species_Flower      150 non-null    object
dtypes: object(5)
memory usage: 7.0+ KB


In [8]:
df.isnull().sum()

Sepal_Length_in_cm    0
Sepal_Width_in_cm     0
Petal_Length_in_cm    0
Petal_Width_in_cm     0
Species_Flower        0
dtype: int64

In [9]:
df.describe()

Sepal_Length_in_cm Sepal_Width_in_cm Petal_Length_in_cm  \
count                 150               150                150   
unique                 35                23                 43   
top                   5.0               3.0                1.5   
freq                   10                26                 14   

       Petal_Width_in_cm Species_Flower  
count                150            150  
unique                22              3  
top                  0.2    Iris-setosa  
freq                  28             50

SPLITTING THE DATASET

In [10]:
x = df[['Sepal_Length_in_cm', 'Sepal_Width_in_cm', 'Petal_Length_in_cm', 'Petal_Width_in_cm']]
y = df['Species_Flower']
df1 = x

TRANSFORMING THE DATASET

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [12]:
data_x = scaler.fit_transform(x.values)
df2 = pd.DataFrame(data_x, index = x.index, columns = x.columns)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df2.values, y, test_size = 0.2, random_state=42)

In [14]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [15]:
from keras.utils import np_utils
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, num_classes = 3)
y_test = to_categorical(y_test, num_classes = 3)

In [16]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120, 3)
(30, 3)


BUILDING MODEL

In [18]:
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=4))
model.add(Dense(3, activation='softmax'))
sgd = SGD(lr = 0.01, momentum = 0.9, nesterov=True)
model.compile(optimizer=sgd,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

PRINTING HISTORY FOR EPOCHS = 100

In [19]:
history = model.fit(X_train, y_train, epochs = 100, batch_size = 32)

Epoch 1/100
4/4 [==============================] - 1s 12ms/step - loss: 1.1901 - accuracy: 0.1917
Epoch 2/100
4/4 [==============================] - 0s 6ms/step - loss: 1.0054 - accuracy: 0.5583
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 0.7970 - accuracy: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 0.6340 - accuracy: 0.7917
Epoch 5/100
4/4 [==============================] - 0s 7ms/step - loss: 0.5295 - accuracy: 0.8167
Epoch 6/100
4/4 [==============================] - 0s 7ms/step - loss: 0.4651 - accuracy: 0.8167
Epoch 7/100
4/4 [==============================] - 0s 6ms/step - loss: 0.4202 - accuracy: 0.8417
Epoch 8/100
4/4 [==============================] - 0s 6ms/step - loss: 0.3879 - accuracy: 0.8333
Epoch 9/100
4/4 [==============================] - 0s 7ms/step - loss: 0.3657 - accuracy: 0.8500
Epoch 10/100
4/4 [==============================] - 0s 6ms/step - loss: 0.3438 - accuracy: 0.8583
Epoch 11/100
4/4 [==========

PRINTING THE SCORE

In [20]:
score = model.evaluate(X_test, y_test, verbose = 0)

In [21]:
print('Test score:', score[0])
print('Test accuracy:', score[1])

Test score: 0.05914933234453201
Test accuracy: 1.0


CONFUSION MATRIX

In [22]:
y_pred = model.predict(X_test)

1/1 [==============================] - 0s 103ms/step


In [23]:
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


#**THANK YOU!!**